### ISSUE TITLE
FatalErrorException with Laravel v5.1.10

### ISSUE THREAD

**Issue by jbellomy** [mybb/gravatar#2]
Installing dev-master with Laravel v5.1.10 generates the following exception:
FatalErrorException in GravatarServiceProvider.php line 52:
Call to undefined method Illuminate\Config\Repository::package()

I have created a working service provider which I'll send with a pull request, however I haven't verified that it works with Laravel 5.0.

**Comment by JN-Jones** [comment]
Aparrently this wasn't closed automatically though it was fixed in #3
